[core]
Address = ":8080"
WebPrefix = "/"
TemplateDir = "./templates/"

[core.html]
Title = "Go WakeOnLan server"

[workstations]

[workstations.vaih-workstation-1]
NAME = "VAIH-Workstation-1"
MAC = "14:da:e9:de:d5:0b"
IP = "100.126.240.33"
LINK = "https://www.google.at"

[workstations.vaih-workstation-2]
NAME = "VAIH-Workstation-2"
IP = "100.126.240.34"
MAC = "14:da:e9:de:d6:30"
LINK = "https://www.google.at"
