[core]
Address = ":8080"
ExternalURL = ""
TemplateDir = "./templates/"

[core.html]
Title = "Go WakeOnLan server"

[workstations]

[workstations.vaih-workstation-1]
MAC = "14:da:e9:de:d5:0b"
IP = "100.126.240.33"

[workstations.vaih-workstation-2]
IP = "100.126.240.34"
MAC = "14:da:e9:de:d6:30"
