[core]
Address = "127.0.0.1:8080"
WebPrefix = "/"
TemplateDir = "./templates/"
Scheduler = "1m"

[core.html]
Title = "Go WakeOnLan server"

[workstations]

[workstations.example1]
NAME = "Example-1"
MAC = "14:da:55:55:55:55"
IP = "100.100.100.100"
LINK = "https://www.google.at"

[workstations.example2]
NAME = "Example-2"
IP = "100.100.100.100"
MAC = "14:da:55:55:55:55"
LINK = "https://www.google.at"
